fender/urls.py
from django.urls import path
from . import views

app_name = 'fender'

urlpatterns = [
    path('', views.view_home, name="home"),
    path('produtos', views.view_produtos, name="produtos"),
    path('produtos/produto/<int:id>', views.view_produto, name='produto'),
]

guitars/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('ibanez/', include('ibanez.urls')),
    path('fender/', include('fender.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'inicio'

urlpatterns = [
    path('', views.view_home, name='home'),
]

ibanez/urls.py
from django.urls import path
from . import views

app_name = 'ibanez'

urlpatterns = [
    path('', views.view_home, name='home'),
    path('produtos/', views.view_produtos, name='produtos'),
    path('produtos/produto/<int:id>', views.view_produto, name='produto'),
]

fender/models.py
from django.db import models

class TipoFender(models.Model):
    nome = models.CharField(max_length=100)
    estilo = models.CharField(max_length=50, default=' ')
    descricao = models.CharField(max_length=500)
    emEstoque = models.BooleanField()
    preco = models.IntegerField()
    data_lanc = models.DateField()
    slug = models.SlugField()
    foto = models.ImageField(upload_to='imagens/%Y/%m/%D')
    
    def __str__(self):
        return self.nome
    

home/models.py
from django.db import models

# Create your models here.

ibanez/models.py
from django.db import models

class Tipo(models.Model):
    nome = models.CharField(max_length=100)
    estilo = models.CharField(max_length=50)
    descricao = models.CharField(max_length=500)
    emEstoque = models.BooleanField()
    preco = models.IntegerField()
    data_lanc = models.DateField()
    slug = models.SlugField()
    foto = models.ImageField(upload_to='imagens/%Y/%m/%D')
    
    def __str__(self):
        return self.nome
    

fender/views.py
from django.shortcuts import render
from . import models

def view_home(request):
    return render(request, 'fender/paginas/index.html')

def view_produto(request, id):
    resultado = models.TipoFender.objects.get(id = id)
    resultado = resultado.__dict__
    print(resultado)
    return render(request, 'fender/paginas/produto.html', context=resultado
                  )

def view_produtos(request):
    produtos = []
    tipos = models.TipoFender.objects.filter(emEstoque = True)
    for i in tipos:
        produtos.append(i.__dict__)
    return render(request, 'fender/paginas/produtos.html', context={'dicionario':produtos}
                  )

home/views.py
from django.shortcuts import render
from . import views

def view_home(request):
    return render(request, 'home/paginas/index.html')

ibanez/views.py
from django.shortcuts import render
from . import models

def view_home(request):
    return render(request, 'ibanez/paginas/index.html')

def view_produto(request, id):
    resultado = models.Tipo.objects.get(id = id)
    return render(request, 'ibanez/paginas/produto.html', context={'dicionario':resultado}
                  )

def view_produtos(request):
    produtos = []
    tipos = models.Tipo.objects.filter(emEstoque = True)
    for i in tipos:
        produtos.append(i.__dict__)
    return render(request, 'ibanez/paginas/produtos.html', context={'dicionario':produtos}
                  )

fender/templates/fender/paginas/index.html
{% extends 'global/base_index.html' %}
{% load static %}

{% block css_app %}
    <link rel="stylesheet" href="{% static 'fender/css/main.css' %}" />
{% endblock css_app%}

{% block titulo %}{% endblock titulo %}

{% block home_url %}
    "{% url 'fender:home' %}"
{% endblock home_url %}

{% block produtos_url %}
    "{% url 'fender:produtos'%}"
{% endblock produtos_url %}

{% block header_texto %}
    Fender
{% endblock header_texto %}

{% block foto %}
    src="{% static 'global/img/Screenshot_7.png' %}"
{% endblock foto%}

<scritpt type="text/javascript" src="{% static 'fender/js/main.js' %}"></script>

fender/templates/fender/paginas/produto.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'fender/parciais/head.html' %}
<body>
    {% include 'fender/parciais/header.html' %}
        <div class="container">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">{{ nome }}</h3>
                    <h6 class=""> Melhor 
                        {% if estilo == 'acustica' %}
                            violão
                        {% elif estilo == 'eletrica' %}
                            guitarra
                        {% else %}
                            Ukulele
                        {% endif %}
                         do Mercado</h6>
                    <div class="row">
                        <div class="col-lg-5 col-md-5 col-sm-6">
                            <div class="white-box text-center"><img src="../../../imagens/{{ foto }}" class="img-fluid"></div>
                        </div>
                        <div class="col-lg-7 col-md-7 col-sm-6">
                            <h4 class="box-title mt-5">Descrição do Produto</h4>
                            <p>{{ descricao }}</p>
                            <h2 class="mt-5">
                                ${{ preco }}
                            </h2>
                            <p>{{ data_lanc }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>



    <!-- specs -->
    <!-- other products-->

    {% include 'global/footer.html' %}
    <scritpt type="text/javascript" src="{% static 'fender/js/main.js' %}"></script>
</body>
</html>

fender/templates/fender/paginas/produtos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'fender/parciais/head.html' %}
<body>
    {% include 'fender/parciais/header.html' %}

    <div class="row row-cols-3 d-flex justify-content-center">
        {% for produto in dicionario %}
            {% if produto.emEstoque == True %}
                <div class="card m-3" style="width: 18rem;">
                    <img src="../../imagens/{{ produto.foto }}" class="card-img-top" alt="...">
                    <div class="card-body">
                    <h5 class="card-title">{{produto.nome}}</h5>
                    <p class="card-text">{{produto.descricao}}</p>
                    <a href="produtos/produto/{{produto.id}}" class="btn btn-primary">Checar Item</a>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% include 'global/footer.html' %}
    <scritpt type="text/javascript" src="{% static 'fender/js/main.js' %}"></script>
</body>
</html>

fender/templates/fender/parciais/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'fender/css/main.css' %}" />
    <title>Document</title>
</head>

fender/templates/fender/parciais/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'inicio:home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'fender:home' %}">Fender <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'fender:produtos' %}">Produtos </a>
        </li>
      </ul>
    </div>
  </nav>

home/templates/home/paginas/index.html
{% include 'global/head.html' %}
<ul>
    <li><a href="{% url 'fender:home' %}">Fender</a></li>
    <li><a href="{% url 'ibanez:home' %}">Ibanez</a></li>
</ul>

{% include 'global/footer.html' %}

ibanez/templates/ibanez/paginas/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'ibanez/parciais/head.html' %}
<body>
    {% include 'ibanez/parciais/header.html' %}
    <img src="{% static 'global/img/Screenshot_6.png' %}"/>
    {% include 'global/footer.html' %}
    <scritpt type="text/javascript" src="{% static 'ibanez/js/main.js' %}"></script>
</body>
</html>

ibanez/templates/ibanez/paginas/produto.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'ibanez/parciais/head.html' %}
<body>
    {% include 'ibanez/parciais/header.html' %}

    {%  if dicionario.id == dicionario.id %}
        <div class="container">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">{{ dicionario.nome }}</h3>
                    <h6 class=""> Melhor 
                        {% if dicionario.estilo == 'acustica' %}
                            violão
                        {% elif dicionario.estilo == 'eletrica' %}
                            guitarra
                        {% else %}
                            Baixo
                        {% endif %}
                         do Mercado</h6>
                    <div class="row">
                        <div class="col-lg-5 col-md-5 col-sm-6">
                            <div class="white-box text-center"><img src="../../../imagens/{{ dicionario.foto }}" class="img-fluid"></div>
                        </div>
                        <div class="col-lg-7 col-md-7 col-sm-6">
                            <h4 class="box-title mt-5">Descrição do Produto</h4>
                            <p>{{ dicionario.descricao }}</p>
                            <h2 class="mt-5">
                                ${{ dicionario.preco }}
                            </h2>
                            <p>{{ dicionario.data_lanc }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>



    <!-- specs -->
    {% endif %}
    <!-- other products-->

    {% include 'global/footer.html' %}
    <scritpt type="text/javascript" src="{% static 'ibanez/js/main.js' %}"></script>
</body>
</html>

ibanez/templates/ibanez/paginas/produtos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'ibanez/parciais/head.html' %}
<body>
    {% include 'ibanez/parciais/header.html' %}

    <div class="row row-cols-3 d-flex justify-content-center">
        {% for produto in dicionario %}
            {% if produto.emEstoque == True %}
                <div class="card m-3" style="width: 18rem;">
                    <img src="../../imagens/{{ produto.foto }}" class="card-img-top" alt="...">
                    <div class="card-body">
                    <h5 class="card-title">{{produto.nome}}</h5>
                    <p class="card-text">{{produto.descricao}}</p>
                    <a href="produto/{{produto.id}}" class="btn btn-primary">Checar Item</a>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% include 'global/footer.html' %}
    <scritpt type="text/javascript" src="{% static 'ibanez/js/main.js' %}"></script>
</body>
</html>

ibanez/templates/ibanez/parciais/footer.html
<footer class="bg-light text-center text-lg-start">
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      This site was made by
      <a class="text-dark" href="https://github.com/Hollow-Soul/" target="_blank">Fabrício Rech</a>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

ibanez/templates/ibanez/parciais/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'ibanez/css/main.css' %}" />
    <title>Document</title>
</head>

ibanez/templates/ibanez/parciais/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'inicio:home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'ibanez:home' %}">Ibanez <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ibanez:produtos' %}">Produtos </a>
        </li>
      </ul>
    </div>
  </nav>